llm/cli.py
Add a new option to use the conversation mode (or continuation mode). 
```bash
$ llm "What is a pie?"
A pie is a baked dish typically made of a pastry crust filled with sweet or savory ingredients such as fruit, meat, vegetables, or custard. Pies can either be open-faced or have a top crust and are often served as a dessert or a main dish.
```
Use the `-c` flag with no arguments to continue the previous prompt. 
```bash
$ llm "Can it be made gluten-free?" -c 
Yes, pies can be made gluten-free by using ingredients that do not contain gluten such as rice, corn, or almond flour for the crust. Additionally, gluten-free pies can be made with alternative binders, such as xanthan gum or cornstarch, to help create a cohesive and stable filling. There are numerous recipes available for gluten-free …
```
=> -c option for continuing a chat (using new chat_id column)

llm/cli.py
also added a `3.5` alias
fixes https://github.com/simonw/llm/issues/37
=> add 16k models

README.md, docs/conf.py, docs/index.md
=> Rename llm to LLM

docs/help.md, docs/logging.md, llm/__init__.py, llm/cli.py, llm/migrations.py, llm/models.py, tests/test_llm.py, tests/test_migrate.py, tests/test_templates.py
=> Log and load conversations from new DB schema

docs/plugins/tutorial-model-plugin.md
Thank you for the useful CLI tool for LLMs!
I found a very minor typo in the doc and this PR fixes it.
=> Fix a typo

docs/embeddings/cli.md, docs/help.md, llm/cli.py, llm/embeddings.py, tests/test_embed_cli.py
=> llm embed-multi command

docs/help.md, docs/index.md, docs/logging.md, docs/usage.md, llm/cli.py, tests/conftest.py, tests/test_chat.py
=> llm chat command

README.md
=> docs: fix typo 7b -> 13b

docs/aliases.md, docs/changelog.md, docs/usage.md, llm/default_plugins/openai_models.py, setup.py
=> Add GPT 4 turbo model and -o seed 1 option

docs/plugins/directory.md
Link to plugin that integrates with Ollama
=> Add ollama to plugin directory

.github/workflows/test.yml, tests/test-llm-load-plugins.sh
=> Run test-llm-load-plugins.sh

llm/default_plugins/openai_models.py
=> Use model_dump() instead of dict()

docs/openai-models.md
=> Update openai-models.md to fix 'Adding more OpenAI models' section

README.md
=> tiny typo on README.md

llm/default_plugins/openai_models.py, llm/migrations.py, llm/models.py, tests/test_cli_openai_models.py, tests/test_llm.py
=> Fix for UTC warnings

docs/index.md
Add documentation on how to install the llm cli using uv
=> Add installation docs with uv

docs/plugins/directory.md
Based on the llm-fireworks plugin.
=> Add `llm-deepseek` plugin

docs/help.md, docs/logging.md, llm/cli.py, tests/test_llm.py
=> llm logs --prompts option

docs/embeddings/cli.md, docs/help.md, llm/cli.py, tests/test_embed_cli.py
=> llm embed-multi --prepend option

docs/templates.md, llm/cli.py, llm/templates.py, tests/test_templates.py
=> Ability to store options in templates

docs/help.md, docs/usage.md, llm/cli.py, tests/test_cli_options.py
=> options family of commands for setting default options

llm/cli.py
=> On Windows check for `c:...` path existence before executing plugins

docs/fragments.md, docs/plugins/plugin-hooks.md, llm/__init__.py, llm/cli.py, tests/conftest.py, tests/test_plugins.py
=> Fragment plugins can now optionally return attachments

docs/help.md, llm/cli.py, tests/test_chat.py, tests/test_llm.py
Fixes the issue reported in:
-  https://github.com/simonw/llm/issues/933
Also adds ``--database`` argument to ``llm chat``
=> Fixes `--continue` bug and adds `--database` argument to `llm chat`

docs/openai-models.md, docs/usage.md, llm/default_plugins/openai_models.py
This is the newest model released by OpenAI and is available through the API.
=> llm/default_plugins: add o3 model

docs/help.md, docs/usage.md, llm/cli.py, llm/models.py, pyproject.toml, tests/conftest.py, tests/test_chat.py, tests/test_plugins.py
=> llm chat --tool and --functions

docs/python-api.md, llm/default_plugins/openai_models.py, llm/models.py, pyproject.toml, tests/conftest.py, tests/test_tools.py
=> Async tool support

docs/plugins/directory.md, docs/plugins/plugin-hooks.md
This PR documents the register_embedding_models hook
=> document register_embedding_models hook

docs/plugins/directory.md
adds llm-tools-exa, llm-tools-rag, llm-fragments-site-text, and llm-fragments-pdf
i'm also open to feedback on any and all of these plugins, esp llm-tools-rag which can probably be both improved and/or potentially built into the core package
=> add four new plugins to directory
