simonw/llm

- docs/conf.py
- docs/index.md
- docs/setup.md
- docs/templates.md
- llm/__init__.py
- llm/cli.py
- setup.py
- tests/conftest.py
- tests/test_keys.py
- tests/test_templates.py
> WIP: templates

- docs/templates.md
- llm/__init__.py
- tests/test_templates.py
This allows default values to be filled for templates.
For example:
```yaml
prompt: Summarize this text in the voice of $voice
defaults:
voice: GlaDOS
```
When running without `-p` it will choose the default:
```bash
curl -s 'https://til.simonwillison.net/macos/imovie-slides-and-audio' | \
strip-tags -m | llm -t summarize
```
But you can override the defaults with `-p`:
```bash
curl -s 'https://til.simonwillison.net/macos/imovie-slides-and-audio' | \
strip-tags -m | llm -t summarize -p voice Yoda
```
I got this:
> Text, summarize in Yoda's voice, I will: "Hmm, young padawan. Summary of this text, you seek. Hmmm. ...
> Add a defaults parameter to templates.

- docs/templates.md
In the previous example we create a template with the name summarize so it makes sense that the following example it's called the same.
> Update templates.md ~ summary -> summarize 

- llm/cli.py
A TypeError is getting triggered when running the command `llm templates list` if a template contains an empty prompt.
To reproduce the issue, quickly close the editor after using the `llm templates edit new-prompt-name` command.
For reference, here's a snippet of the traceback:
```
File ".../lib/python3.9/site-packages/llm/cli.py", line 545, in templates_list
pairs.append((name, "".join(text).replace("\n", " ")))
TypeError: sequence item 0: expected str instance, NoneType found
```
> Fix for TypeError in `llm templates list` when template contains empty prompt

- .gitignore
- llm/default_plugins/openai_models.py
- tests/test_cli_openai_models.py
Closes this [issue](https://github.com/simonw/llm/issues/115).
```
llm -m chatgpt 'say hello twice' -o temperature -1
Error: temperature
Input should be greater than or equal to 0
```
> Set min/max constraints to float arguments

- llm/default_plugins/openai_models.py
- llm/models.py
- setup.py
Use v1-style configuration. While this is officially
deprecated (https://docs.pydantic.dev/latest/usage/model_config/),
it is supported by v2. I would assume this support will remain
for a while, this will help ease the transition to v2.
Background: llm may be used in combination with other libraries that may directly or indirectly depend on pydantic v1, this PR is designed to give groups the ability to combine llm with their other libraries and have some breathing space to transition
> Allow for use of Pydantic v1 as well as v2.

- docs/embeddings/binary.md
- docs/embeddings/cli.md
- docs/embeddings/index.md
- docs/embeddings/writing-plugins.md
- docs/help.md
- docs/index.md
- llm/__init__.py
- llm/cli.py
- llm/default_plugins/openai_models.py
- llm/embeddings_migrations.py
- llm/hookspecs.py
- llm/models.py
- mypy.ini
- setup.py
- tests/conftest.py
- tests/test_embed.py
- tests/test_embed_cli.py
> Initial CLI support and plugin hook for embeddings

- llm/cli.py
- tests/test_embed_cli.py
Hey, just an improvement on the error message for missing default embedding model. I was confused with default models here (thought it was asking me for a LLM model)
> Updated error message for invalid or missing embedding model

- docs/help.md
- llm/cli.py
The type of the "content" argument was erroneously set to be FILE with a "type=click.Path(...)" argument, which content is a string.
> change type of cli "embed -c" to be STR not FILE

- llm/cli.py
- tests/test_embed_cli.py
This PR resolves issues in #274, and #280
> Fix issues: #274, #280

- .github/workflows/test.yml
- docs/contributing.md
- llm/cli.py
- llm/default_plugins/openai_models.py
- llm/embeddings.py
- llm/utils.py
- setup.py
- tests/conftest.py
- tests/test_cli_openai_models.py
- tests/test_keys.py
- tests/test_llm.py
- tests/test_templates.py
Refs:
- #325
Original goal was "Upgrade to run against both OpenAI < 1.0 and OpenAI >= 1.0" but I eventually determined that the changes between the two were just too extensive for it to be worth trying to build a compatibility shim.
> Upgrade to run against OpenAI >= 1.0

- .github/workflows/test.yml
- docs/changelog.md
- setup.py
- tests/test_chat.py
- tests/test_embed_cli.py
- tests/test_keys.py
- tests/test_llm.py
> Run CI against macOS and Windows too

- docs/usage.md
Looks like this alias was overlooked in 8171c9a. This commit makes it
match with the usage of gpt-4o in the associated example.
> Update outdated reference to gpt-4-turbo

- docs/openai-models.md
- docs/usage.md
- llm/default_plugins/openai_models.py
> o1-preview and o1-mini

- .github/workflows/publish.yml
- .github/workflows/test.yml
- setup.py
- tests/test_keys.py
- tests/test_templates.py
A number of tests are failing on main, apparently because tests always use the latest version of every dependency (no `Pipfile.lock`) and e.g. `pytest_httpx` has breaking changes.
Also `pytest_httpx` now requires python>=3.9 so I dropped 3.8 support.
What do you think about switching from `setup.py` to isolated builds using `uv` and checking in a `uv.lock` so tests don't fail over time?
```
=========================== short test summary info ============================
FAILED tests/test_keys.py::test_uses_correct_key - assert 1 == 0
FAILED tests/test_templates.py::test_template_basic[boo-extra_args3-None-None-Error: Cannot use -t/--template and --system together] - TypeError: HTTPXMock.reset() got an unexpected keyword argument 'assert_all...
FAILED …
```
> Fix broken tests.  Drop python 3.8.

- docs/other-models.md
- llm/default_plugins/openai_models.py
Fixes #599 
A longer term fix would be to use something like Pydantic so we don't repeat ourselves, but this would be a bit of a refactor
> Allow passing of can_stream in openai_models.py

- .github/workflows/cog.yml
- docs/logging.md
> Run cog -r in PRs, use that to update logging.md with new tables

- docs/usage.md
The default model is now 4o-mini; this change updates the usage page of the docs to reflect that
> Update default model information to 4o-mini

- docs/plugins/directory.md
Adds`llm-grok` xAI API (https://github.com/Hiepler/llm-grok) to the plugin directory.
> docs: add llm-grok

- docs/help.md
- docs/logging.md
- docs/plugins/advanced-model-plugins.md
- llm/cli.py
- llm/default_plugins/openai_models.py
- llm/migrations.py
- llm/models.py
- llm/utils.py
- tests/conftest.py
- tests/test_chat.py
- tests/test_cli_openai_models.py
- tests/test_llm.py
- tests/test_migrate.py
- tests/test_utils.py
Refs:
- #610
TODO:
- ~Document how to use this in the Python API (I'll need this myself for the `datasette-llm` package)~ I need to document `Response` generally, will do this in a new issue.
> Log input tokens, output tokens and token details

- llm/cli.py
This is the issue
On a windows system, llm chat throws an error.
```cmd
llm chat -m l32
```
Fixed. Demo of it working
> Fix windows bug where llm doesn't run <<llm chat>> on Windows issue #495

- docs/plugins/directory.md
By keeping this wonderful plugin in the directory, we can prevent the kind of re-implementation I had to do today.
https://github.com/watany-dev/llm-bedrock-nova
> doc(plugin): adding AmazonBedrock

- docs/usage.md
- llm/cli.py
Show the current default model in the list of models in the list printed by `llm models`.
> Show the default model when listing all available models.

- docs/plugins/directory.md
I made a plugin that makes the llm-cmd plugin much more ergonomic. I'd like to include it in the directory!
Thank you!
> Add llm-cmd-comp to plugin directory

- llm/default_plugins/openai_models.py
- tests/test_aliases.py
- tests/test_embed_cli.py
This update registers the default plugin modules under their full names.
It allows use of the same embedding model names available in ttok.
Aliases for the short names are added for backward compatibility.
> Register full embedding model names

- docs/help.md
- docs/logging.md
- docs/usage.md
- llm/cli.py
- llm/templates.py
- llm/utils.py
- tests/test_llm.py
- tests/test_utils.py
> --xl/--extract-last

- docs/plugins/advanced-model-plugins.md
- docs/plugins/tutorial-model-plugin.md
- docs/python-api.md
- llm/__init__.py
- llm/cli.py
- llm/default_plugins/openai_models.py
- llm/models.py
- tests/conftest.py
- tests/test_llm.py
Refs:
- #744
Still needs:
- (I just noticed that `llm embed` doesn't take a `--key` option - think about that) - #757
> KeyModel and AsyncKeyModel classes for models that taken keys

- .github/workflows/test.yml
- llm/cli.py
- llm/default_plugins/openai_models.py
- llm/models.py
- llm/templates.py
- pytest.ini
- setup.py
> Upgrade to Pydantic v2

- docs/embeddings/cli.md
- docs/help.md
- llm/cli.py
Hi there! Thank you for sharing this great tool.
This is a minor documentation update.
Users like me might want to know what similarity function is used in `similar` commands since there are several similarity functions and modern Vector Search Engines usually support multiple similarity metrics (examples:  [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html#dense-vector-params), [Qdrant](https://qdrant.tech/documentation/concepts/search/#metrics)).
> Add note about similarity function in "similar" command's doc

- docs/changelog.md
- docs/help.md
- docs/logging.md
- docs/plugins/advanced-model-plugins.md
- docs/python-api.md
- docs/usage.md
- llm/cli.py
- llm/default_plugins/openai_models.py
- llm/migrations.py
- llm/models.py
- tests/conftest.py
- tests/test_chat.py
- tests/test_embed_cli.py
- tests/test_llm.py
- tests/test_migrate.py
> llm prompt --schema X option and model.prompt(..., schema=) parameter

- docs/openai-models.md
- llm/default_plugins/openai_models.py
Currently you get an error when trying to use `-o reasoning_effort high` with a model that has been defined in `extra-openai-models.yaml`.  This allows an optional `reasoning` field.
> Allow "reasoning" for extra-openai-models.yaml

- docs/templates.md
- docs/usage.md
- llm/cli.py
- llm/templates.py
- tests/test_templates.py
> Schema template --save --schema support

- docs/other-models.md
- llm/default_plugins/openai_models.py
Recently support for structured output was added. But custom OpenAI-compatible models didn't support the `supports_schema` property in the config file `extra-openai-models.yaml`.
I validated the change by adding the following to my `extra-openai-models.yaml`:
```
- model_id: openai_custom
model_name: gpt-4o-mini
api_base: "https://api.openai.com/v1"
api_key_name: openai
supports_schema: true
```
and observing the output of
```
uv run llm -m openai_custom --schema 'name,age int,short_bio' 'invent a cool dog'
```
> Add supports_schema to extra-openai-models.yaml

- docs/other-models.md
- llm/default_plugins/openai_models.py
Should close https://github.com/simonw/llm/issues/602
`extra-openai-models.yaml` can be used to access OpenAI-compatible models, in my case I use it to access models through a proxy. Certain options supported by OpenAI models when used directly are not supported when using this method.
I noticed something similar for schemas has been merged super-recently https://github.com/simonw/llm/pull/819 so I thought to also do the same for other options, namely vision and audio.
This adds support for OpenAI compatible models specified via the `extra-openai-models.yaml` so that models that support it can receive image and audio attachments
---
tested with
```
- model_id: gw-gpt-4o
model_name: gpt-4o
api_base: "http://localhost:8888/v1/"
vision: true
```
and running
`llm -m gw-gpt-4o "describe this …
> Support vision and audio for extra-openai-models.yaml

- llm/cli.py
Addresses the enhancement issue https://github.com/simonw/llm/issues/759
Now
llm logs --short, produces
```yaml
- model: llama3.2:latest
datetime: '2025-03-08T05:30:12'
conversation: 01jnt3sgj23z38sz6j673p59a3
prompt: import asyncio import click from click_default_group impo...  Explain
this code in detail and with practical examples
```
> --short now shows the end of the prompt too

- docs/openai-models.md
- docs/usage.md
- llm/cli.py
- tests/test_aliases.py
- tests/test_llm.py
Update OpenAI model command to include API key and environment variable details for each model. Adjusted CLI output formatting to reflect these changes.  Updated tests to verify the new output format. Updated the documentation.
```
(venv) stevemorin@Steves-MacBook-Pro-2 docs % python -m llm models
OpenAI Chat: gpt-4o (aliases: 4o, key: openai, env_var: OPENAI_API_KEY)
OpenAI Chat: chatgpt-4o-latest (aliases: chatgpt-4o, key: openai, env_var: OPENAI_API_KEY)
```
> Update OpenAI model command to include API key and environment variables

- docs/templates.md
- llm/templates.py
- tests/test_templates.py
Right now it's impossible to escape a dollar sign on a template, so we can't create a template like the folowing:
```bash
llm 'Does this item cost $10?' --save cost
llm 'What are the contents of my $PATH variable?' --save path
```
This commit allows escaping dollar signs which would allow this:
```bash
llm 'Does this item cost $$10?' --save cost
```
And then we can use the template with:
```bash
llm -t cost "banana"
```
> Allow escaping a dollar sign in templates by adding another dollar sign

- docs/openai-models.md
The documentation doesn't work as-is: if you create a file without model_name, then no calls to llm will work.
> Update doc for extra-openai-models.yaml, include mandatory model_name

- docs/plugins/directory.md
As the name suggests, this plugin gets PyPI packages as fragments.
Namely the project metadata and description.
See README for more usage examples:
https://github.com/samueldg/llm-fragments-pypi?tab=readme-ov-file#usage
> Add llm-fragments-pypi to plugin directory

- docs/embeddings/cli.md
- docs/help.md
- llm/cli.py
- llm/embeddings.py
- tests/test_embed.py
- tests/test_embed_cli.py
This PR complements the `--prefix` arg in `llm embed-multi` with an analogous `--prefix` arg in `llm similar` that filters results by id prefix. This propagates through the various python API similar methods, has a unit test for the underlying functionality and a unit test for the CLI command.
> Filter IDs with `--prefix` in `llm similar`

- README.md
- docs/logging.md
- llm/migrations.py
- llm/models.py
- tests/test_plugins.py
- tests/test_utils.py
> Log tool_instances to database

- README.md
- docs/plugins/plugin-hooks.md
- docs/templates.md
- llm/cli.py
- llm/templates.py
- tests/test_templates.py
> Tools in templates
